package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Monday, 27 November 2023 17:37:49 o'clock IST
*/

public interface EchoOperations 
{
  String echoString ();
} // interface EchoOperations
